directories:
  output: release
  buildResources: build
appId: com.sknow.reverb
productName: Reverb
mac:
  category: public.app-category.developer-tools
  target:
    - dmg
    - zip
  icon: build/icon.icns
win:
  target:
    - nsis
  icon: build/icon.ico
linux:
  target:
    - AppImage
    - deb
  category: Development
files:
  - filter:
      - build/**/*
      - node_modules/**/*
      - package.json
      - main.js
      - preload.js
      - dist/**/*
electronVersion: 31.7.7
