name: Build Check

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build-check:
    name: Build Check (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Verify build
        run: npm run build
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
